[MIDI]
# part of the port name
midi_out = Ssh

[MESSAGES]
# IOS app MidiFire uses it to set BPM
_bpm_msg : [0xF0, 0x5A] + FILL_BYTES(round(BPM * 100), 6) + [0xF7]
# IOS app MidiFire uses it to correct timing
_bar_msg : [0xF0, 0x5B, 0xF7]
# IOS app FunkBox is controlled by MidiFire, some messages passed directly
_stop_msg : [0xFC]
_volume_msg : [0xB0, 8, round(VOLUME * 100)]
# 0 to 35 in FunkBox, use first 12
_progs_list : [1,2,3,4,5,6,7,8,9,10,11,12]
_prog_msg : [0xC0, PROG]

