[MIDI]
# part of the port name
midi_out = Ssh

[MESSAGES]
; if BPM = 1023.56 then BPM_LIST = [1, 0, 2, 3, 5, 6]
; if BPM = 23.78 then BPM_LIST = [0, 0, 2, 3, 7, 8]
; IOS app MidiFire uses sysex with BPM_LIST to synch drums
bpm_msg : [0xF0, 0x5A] + BPM_LIST + [0xF7]
; IOS app MidiFire uses it to correct timing
bar_msg : [[0xF0, 0x5B, 0xF7], [0xC0,  PROG]]
; IOS app FunkBox is controlled by MidiFire, some messages passed directly
stop_msg : [0xFC]
volume_msg : [0xB0, 8, round(VOLUME * 100)]
; 0 to 35 in FunkBox, use first 12
prog_list : [1,2,3,4,5,6,7,8,9,10,11,12]
progs_msg : [0xB0, 60,  PROG]

