# messages processed are: '_bar_msg', '_bpm_msg', '_volume_msg', '_prog_msg', '_progs_param', '_stop_msg'
[MIDI]
midi_out = VALETON GP-100 PRODUCT


[MESSAGES]

bpm_drum : [0xB0, 74 if BPM < 127.5 else 73, round(BPM) if BPM < 127.5 else (round(BPM) - 128)]
bpm_effects : [0xB0, 71 if BPM < 127.5 else 70, round(BPM) if BPM < 127.5 else (round(BPM) - 128)]
_bpm_msg : [%(bpm_drum)s, %(bpm_effects)s]

_progs_param : [10, 90, 72, 66, 3, 89, 27, 5, 4, 70, 69, 84, 29, 83, 75]
_prog_msg : [%(_stop_msg)s, [0xB0, 60, PROG]]

# once over 4 bars stop and start loop
_bar_msg : [%(_stop_msg)s, [0xB0, 59, 0]]
_stop_msg : [0xB0, 59, 127]
_volume_msg : [0xB0, 61, round(VOLUME * 100)]


