[MIDI]
# part of the port name for Valeton GP-100
midi_out = VALETON


[MESSAGES]
# not used
#bpm_effects : [0xB0, 71 if BPM < 127.5 else 70, round(BPM) if BPM < 127.5 else (round(BPM) - 128)]
#set_prog_99 : [0xB0, 60,  99]
#set_prog : [0xB0, 60,  PROG]

# used for substitution
drum_start : [0xB0, 59, 0]
prog_msg : [0xB0, 60,  PROG]

# used by this looper and must be defined
_bpm_msg : [0xB0, 74 if BPM < 127.5 else 73, round(BPM) if BPM < 127.5 else (round(BPM) - 128)
_progs_list : [48, 64, 66, 3, 82, 5, 4, 15, 48, 84, 29, 83, 27]
_stop_msg : [0xB0, 59, 127]
_prog_msg : [0x80, 0, 0]
_volume_msg : [0xB0, 61, round(VOLUME * 100)]
_bar_msg : [%(_stop_msg)s, %(prog_msg)s, %(drum_start)s]


