[MIDI]
# part of the port name for Valeton GP-100
midi_out = VALETON


[MESSAGES]
# options for substitution
bpm_drum : [0xB0, 74 if BPM < 127.5 else 73, round(BPM) if BPM < 127.5 else (round(BPM) - 128)]
bpm_effects : [0xB0, 71 if BPM < 127.5 else 70, round(BPM) if BPM < 127.5 else (round(BPM) - 128)]
set_prog = [0xB0, 60,  PROGIDX]
drum_start = [0xB0, 59, 0]

# MIDI messages
_bpm_msg : [%(bpm_drum)s, %(bpm_effects)s]
_progs_list : [49, 64, 72, 66, 3, 10, 27, 82, 5, 4, 15, 48, 84, 29, 83, 75, 89]
_prog_msg :
_bar_msg : [%(set_prog)s, %(drum_start)s]
_stop_msg : [0xB0, 59, 127]
_volume_msg : [0xB0, 61, round(VOLUME * 100)]


