[AUDIO]
max_len_seconds = 60
sd_rate = 44100
sd_type = int16
# case insensitive device names to use
preffered_list = Valeton, USB Audio, Behringer

[KEYBOARD]
# kbd_notes = "`": 60, "6": 62, "=":64, "-": 65, "x": 12, "/": 13
kbd_notes = "1": 60, "2": 62, "3":64, "4": 65, "q": 12, "w": 13

[MIDI]
midi_in = BlueBoard
midi_out = Ssh

[MENU]
menu_dir = button6

