[Do not change this file, it is restored by update. Edit local.ini]
; audio options
max_len_seconds = -- how long a loop may be.
device_name = -- name (or part of name) of the device to use, case insensitive
device_type = -- data type to process and store audio information, int16 or float32
drum_volume = -- adjust all WAV samples volume if Style or Euclid drums volume need to change
sample_rate = -- sample rate, mostly 48000 and 44100
; midi options
keyboard_keys =  -- 6 keys on computer keyboard if MIDI controller is missing
keyboard_notes = -- 6 notes of MIDI foot controller pedal. Note velocity must be > 10
midi_in =  -- name (or part of name) for MIDI input control, optional
midi_out = --  name (or part of name) for MIDI drum output, optional
; menu options
menu_choice = -- menu layout directory located in /config/menu/ (6 buttons x 4 parts)
; screen options
screen_type = -- where to show looper's info (0 - terminal, 1 - web page)
; drum options
style_break = -- name containing it is a break, if empty break determined by pattern's energy
euclid_break = -- same as above for Euclid drum type

[SCREEN]
screen_type = 0

[AUDIO]
max_len_seconds = 60
device_name = USB Audio
device_type = int16
drum_volume = 0.7
sample_rate = 44100


[MIDI]
keyboard_keys = 1, 2, 3, 4, q, w
keyboard_notes = 60, 62, 64, 65, 12, 13
midi_in = BlueBoard
midi_out = Ssh


[MENU]
menu_choice = 6x4

[DRUM]
style_break = Brk
euclid_break =