; K - how many loops to play in beat pattern
beat_loops_play : 2
; loops from zero to N - beat loops, ex: 0, 1, 2, 3, 4, 5. Any K of them selected randomly to create pattern
beat_loops_total : 5

; K - how many loops to play in break pattern
break_loops_play : 20
; loops from end-N to end are break loops, ex: 3, 4, 5, 6, 7. Any K of them selected randomly to create pattern
break_loop_total : 5