; K - how many loops to play in beat pattern, randomly selected from L loops below
beat_loops_play : 2
; L - total beat loops, taken from the beginning of the list of recorded loops
beat_loops_total : 3

; M - how many loops to play in break pattern, randomly selected from N loops below
break_loops_play : 1
; N - total break loops, taken from the end of the list of recorded loops
break_loop_total : 1


; to fully use this configuration we need to record L + N loops.
; if we record less than L + N loops it still works but beat and break loops may be the same and be less random
; if we record 1 loop it plays as a beat, as a break and never changes