; K - how many loops to play in beat pattern
beat_loops_play : 2
; from zero to N: 0, 1, 2, 3, 4, 5. K of them selected randomly create pattern
beat_loops_total : 3

; J - how many loops to play in break pattern
break_loops_play : 3
; from End-N to End: 3, 4, 5, 6, 7. J of them selected randomly create pattern
break_loop_total : 5