; K - how many loops to play in beat pattern, randomly selected from L loops below
beat_loops_play : 1
; L - total beat loops, taken from the beginning of the list of recorded loops
beat_loops_total : 2

; M - how many loops to play in break pattern, randomly selected from N loops below
break_loops_play : 1
; N - total break loops, taken from the end of the list of recorded loops
break_loop_total : 2
