; K - how many loops to play in beat pattern, randomly selected from L loops below
beat_loops_play : 2
; L - total beat loops, taken from the beginning of the list of recorded loops
beat_loops_total : 3

; M - how many loops to play in break pattern, randomly selected from N loops below
break_loops_play : 1
; N - total break loops, taken from the end of the list of recorded loops
break_loop_total : 2
; fully use this configuration we need to record 5 loops. 
; first 3 will be used for beat pattern and play randomly selected 2 loops
; last 2 will be used for break randomly selecting 1 loop
; if we record less than 5 loops it still works but beat and break loops be the same and less random
