[DEFAULT]
steps : 16
beats : 4
shift : 0
# every 2-nd beat has accent
accent : 2


[bd]
# list - all values are equally probable
steps : 6, 8, 12, 16, 16, 16

[sd]
steps : 5, 6, 8, 8, 8, 12, 16
beats : 2, 3, 4
shift : 0, 1, 2, 3, 4, 5, 6, 7, 8
accent : 2, 3, 4, 5, 6

[ch]
steps : 5, 6, 8, 8, 8, 9, 9, 12, 16
beats : 2, 3, 4, 5
shift : 0, 1, 2, 3, 4, 5, 6, 7, 8
accent : 2, 3, 4, 5, 6


[mt]
steps : 5, 6, 8, 8, 8, 9, 12, 16
beats : 1, 2, 3
shift : 0, 1, 2, 3, 4, 5, 6, 7, 8
accent : 5, 6, 7, 8, 9

[lt]
steps : 5, 6, 8, 8, 8, 9, 12, 16
beats : 1, 2, 3
shift : 0, 1, 2, 3, 4, 5, 6, 7, 8
accent : 5, 6, 7, 8, 9
