[DEFAULT]
# 3 gui buttons on top
gui : [play] [song] [param] [next]
prev : _prev_section
next : _next_section
param : _update_menu param.ini
song : _update_menu song.ini
play : _update_menu play.ini
#commands below are for MIDI controller
12-1 : _prev_section
13-1 : _next_section
12-6 : _update_menu play.ini
13-6 : _update_menu song.ini


[drum_param]
description : %(gui)s drum_param: A1-[audio] A2-[midi] A3-[loop] B1-[vol_dn] B2-[vol_up] C1-[level_dn] C2-[level_up] D1-[random] DH-[delete]
update_method : _show_drum_param
60-1 : _change_drum_type AudioDrum
60-2 : _change_drum_type MidiDrum
60-3 : _change_drum_type LoopDrum

62-1 : _change_volume -1
62-2 : _change_volume 1

64-1 : _change_drum_level -1
64-2 : _change_drum_level 1

65-1 : _random_drum


audio : _change_drum_type AudioDrum
midi : _change_drum_type MidiDrum
loop : _change_drum_type LoopDrum

vol_dn : _change_volume -1
vol_up : _change_volume 1

level_dn : _change_drum_level -1
level_up : _change_drum_level 1

random : _random_drum



[drum_config]
description : %(gui)s drum_config: A1-[go_up] A2-[go_dn] D2-[load]
update_method : _show_drum_config
60-1 : _iterate_drum_config -1
62-1 : _iterate_drum_config 1
65-2 : _load_drum_config: _update_menu play.ini

go_up : _iterate_drum_config -1
go_dn : _iterate_drum_config 1
load : _load_drum_config: _update_menu play.ini


 
