[default]
; this is included in all sections
E1 : _menu_part undo: update
E2 : _menu_part redo: update
E3 : _menu_stop

E6 : menu
E7 : menu song
E8 : menu serv

F1 : _menu_drum randomize
F2 : _menu_drum fill
F3 : _menu_drum stop
F6 : _menu_stop faster

[play.0]
description : parts A..D-play E-drum
show : _show_parts
; play and record
A100 : _menu_part_select 0: update
B100 : _menu_part_select 1: update
C100 : _menu_part_select 2: update
D100 : _menu_part_select 3: update

A3 : _menu_part three_tap
B3 : _menu_part three_tap
C3 : _menu_part three_tap
D3 : _menu_part three_tap

A6 : _menu_part one_tap_hold: update
B6 : _menu_part one_tap_hold: update
C6 : _menu_part one_tap_hold: update
D6 : _menu_part one_tap_hold: update

[play.1]
description : loops A1-next AH-prev B1-silent B2-move BH-delete C1-stop C2-st_fast C3-st_faster
show : _show_loops
A1 : _menu_loop next: update
A6 : _menu_loop prev: update

B1 : _menu_loop silent: update
B2 : _menu_loop move: update
B6 : _menu_loop delete: update

C1 : _menu_stop: menu play
C2 : _menu_stop fast: menu play
C3 : _menu_stop faster: menu play




