[default]
; this is included in all sections
E1 : _menu_part undo
E2 : _menu_part redo
E3 : _menu_part redo_all

E6 : _menu_change
E7 : _menu_change song
E8 : _menu_change serv

F1 : _menu_drum randomize
F2 : _menu_drum break
F3 : _menu_drum stop
F6 : _menu_stop faster

[play.0]
description : parts A..D-play E-drum
show : _show_parts
; play and record
A100 : _menu_part_select 0
B100 : _menu_part_select 1
C100 : _menu_part_select 2
D100 : _menu_part_select 3

A1 : _menu_part overdub
B1 : _menu_part overdub
C1 : _menu_part overdub
D1 : _menu_part overdub

A2 : _menu_part arm
B2 : _menu_part arm
C2 : _menu_part arm
D2 : _menu_part arm

A3 : _menu_part change_fast
B3 : _menu_part change_fast
C3 : _menu_part change_fast
D3 : _menu_part change_fast

A6 : _menu_part clear_next
B6 : _menu_part clear_next
C6 : _menu_part clear_next
D6 : _menu_part clear_next

[play.1]
description : loops A1-next AH-prev B1-silent B2-move B3-merge BH-delete
show : _show_loops
A1 : _menu_loop next
A6 : _menu_loop prev

B1 : _menu_loop silent
B2 : _menu_loop move
B3 : _menu_loop merge
B6 : _menu_loop delete




