[DEFAULT]
# 3 gui buttons on top
gui : [play] [song] [param] [next]
prev : _prev_section
next : _next_section
param : _update_menu param.ini
song : _update_menu song.ini
play : _update_menu play.ini
#commands below are for MIDI controller
12-6 : _next_section
13-6 : _update_menu song.ini
12-1 : _random_drum
12-2 : _change_drum_level -1
12-3 : _change_drum_level 1
12-7 : _stop_drum
13-1 : _undo_part
13-2 : _redo_part
13-3 : _redo_all

[parts]
description : %(gui)s parts: A/B/C/D-play/record
update_method : _show_parts
60-100 : _select_part 0
62-100 : _select_part 1
64-100 : _select_part 2
65-100 : _select_part 3
60-2 : _record_selected
62-2 : _record_selected
64-2 : _record_selected
65-2 : _record_selected
60-6 : _clear_part 0
62-6 : _clear_part 1
64-6 : _clear_part 2
65-6 : _clear_part 3

[loops]
description : %(gui)s loops: A/B-scroll C-vol. D-edit
update_method : _show_loops
60-100 : _change_loop -1
62-100 : _change_loop 1
64-1 : _change_loop_volume 0.8
64-2 : _change_loop_volume 1.2
65-1 : _edit_loop silent
65-2 : _edit_loop reverse
65-3 : _edit_loop move
65-6 : _edit_loop delete
#commands below are for touch screen controller
volume_dn : _change_loop_volume 0.8
volume_up : _change_loop_volume 1.2
go_up : _change_loop -1
go_dn : _change_loop 1
silent : _edit_loop silent
reverse : _edit_loop reverse
move : _edit_loop move
delete : _edit_loop delete