[default]
; this is included in all sections
E1 : menu
E6 : menu play
E7 : menu song
E8 : menu serv

F1 : _menu_drum randomize
F2 : _menu_drum fill
F3 : _menu_drum stop
F6 : _menu_stop faster


[song.0]
description : song A1-next A2-load AH-prev B1-clear B2-save BH-delete
show : _show_song_list
A1 : _menu_song next: update
A2 : _menu_song load: menu play
A6 : _menu_song prev: update

B1:  _menu_song clear: menu play
B2:  _menu_song save: update
B6 : _menu_song delete: update


[song.1]
description : drum config. A1-next A2-load AH-prev
show : _show_config_list
A1 : _menu_drum next: update
A2 : _menu_drum_config: menu play
A6 : _menu_drum prev: update


