[default]
; this is included in all sections
E1 : _menu_change
E6 : _menu_change play
E7 : _menu_change song
E8 : _menu_change serv

F1 : _menu_drum randomize
F2 : _menu_drum break
F3 : _menu_drum stop
F6 : _menu_stop fast


[section to list songs, load, save, clear]
description : song A1/2-scroll AH-clear B1-load B2-save BH-delete
show : _show_song_list
A1 : _menu_song next
A2 : _menu_song prev
A6 : _menu_song clear: _menu_change play

B1 : _menu_song load: _menu_change play
B2 : _menu_song save: _menu_change play
B6 : _menu_song delete


[section to change drum style for song]
description : drum config A1/2-scroll B1-load
show : _show_config_list
A1 : _menu_drum next
A2 : _menu_drum prev

B1 : _menu_drum_config: _menu_change play

