
[Afro1A 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
rs: ......!...!...!.
bd: !.......!.......
[Afro1B 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
rs: ......!.....!...
bd: !.......!.!...!.
[Afro1Brk 4/4]
#...1234567890123456
ac: ....!.......!..!
ch: !...............
mt: ......!!!!!.....
sd: .!!!!...........
lt: ............!!!!
bd: !...............
[Afro2A 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
mt: ..........!.....
rs: ...!..!.........
lt: ............!.!.
bd: !.......!.......
[Afro2B 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
mt: ..........!.!...
rs: ......!.........
bd: !.......!.....!.
[Afro2Brk 4/4]
#...1234567890123456
ac: ............!!..
ch: .............!..
mt: ....!...........
sd: !!..........!...
lt: ......!.!.!.....
bd: .............!..
[Afro3A 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
mt: ......!...!.....
rs: ...!............
lt: ..............!.
bd: !.......!.....!.
[Afro3B 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
mt: ......!...!.....
sd: ...!............
lt: ............!.!.
bd: !.......!.......
[Afro3Brk 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !...!.!...!.!...
mt: ..!!....!!....!!
sd: .!...!.!...!.!..
bd: !...!.!...!.!...
[Afro4A 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
rs: ......!.....!...
bd: !.......!.!...!.
[Afro4B 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
mt: ..........!.....
rs: ......!.........
lt: ..............!.
bd: !.......!.......
[Afro4Brk 4/4]
#...1234567890123456
ac: ............!...
ch: ............!...
ht: ....!.!.........
sd: !..!........!...
lt: ........!.!.....
[Afro5A 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
ht: ..........!.....
rs: ......!.........
lt: ..............!.
bd: !.......!.......
[Afro5B 4/4]
#...1234567890123456
ch: !.!!!.!.!.!.!.!.
rs: ....!.....!.....
bd: !.....!.!.....!.
[Afro5Brk 4/4]
#...1234567890123456
mt: ..........!.....
sd: !.!...!.........
lt: ..............!.

