; drum styles. bd-sound from bd.wav file, ch-from ch.wav, etc. ac-step accent not a sound.
; ac-accent, bd-bass drum, cb-cow bell, ch-close hat, cp-clap, cy-cymbals, ht-hi tom
; lt-low tom, mt-mid tom, oh-open hat, rs-rim shot, sd-snare drum
; styles having 'brk' in the name are break/fill styles, others are normal beats


[beat_001]
ac: ................
bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
lt: ............!.!.
mt: ..........!.....
rs: ...!..!.........


[beat_004]
ac: ................
bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
lt: ..............!.
mt: ..........!.....
rs: ......!.........


[beat_005]
ac: ................
bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
rs: ......!...!...!.


[beat_006]
ac: ................
bd: !.......!.!...!.
ch: !.!!!.!.!.!.!.!.
rs: ......!.....!...


[beat_007]
ac: ................
bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
ht: ..........!.....
lt: ..............!.
rs: ......!.........


[beat_008]
ac: ................
bd: !.......!.!...!.
ch: !.!!!.!.!.!.!.!.
rs: ......!.....!...


[beat_009]
ac: ................
bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
lt: ............!.!.
mt: ......!...!.....
sd: ...!............


[beat_010]
ac: ................
bd: !.....!.!.....!.
ch: !.!!!.!.!.!.!.!.
rs: ....!.....!.....


[beat_011]
ac: ................
bd: !.......!.....!.
ch: !.!!!.!.!.!.!.!.
mt: ..........!.!...
rs: ......!.........


[beat_012]
ac: ................
bd: !.......!.....!.
ch: !.!!!.!.!.!.!.!.
lt: ..............!.
mt: ......!...!.....
rs: ...!............


[break_002]
ac: !...!...!...!...
bd: !...!.!...!.!...
ch: !...!.!...!.!...
mt: ..!!....!!....!!
sd: .!...!.!...!.!..


[break_003]
ac: ............!!..
bd: .............!..
ch: .............!..
lt: ......!.!.!.....
mt: ....!...........
sd: !!..........!...


[break_013]
ac: ....!.......!..!
bd: !...............
ch: !...............
lt: ............!!!!
mt: ......!!!!!.....
sd: .!!!!...........


[break_014]
ac: ............!...
ch: ............!...
ht: ....!.!.........
lt: ........!.!.....
sd: !..!........!...


[break_015]
ac: ................
lt: ..............!.
mt: ..........!.....
sd: !.!...!.........
