; drum styles. bd-sound from bd.wav file, ch-from ch.wav, etc.
; bd-bass drum, cb-cow bell, ch-close hat, cp-clap, cy-cymbals, ht-hi tom
; lt-low tom, mt-mid tom, oh-open hat, rs-rim shot, sd-snare drum
; styles having 'break' in the name are break/fill styles, others are normal beats


[beat_001]

bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
lt: ............!.!.
mt: ..........!.....
rs: ...!..!.........


[beat_004]

bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
lt: ..............!.
mt: ..........!.....
rs: ......!.........


[beat_005]

bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
rs: ......!...!...!.


[beat_006]

bd: !.......!.!...!.
ch: !.!!!.!.!.!.!.!.
rs: ......!.....!...


[beat_007]

bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
ht: ..........!.....
lt: ..............!.
rs: ......!.........


[beat_008]

bd: !.......!.!...!.
ch: !.!!!.!.!.!.!.!.
rs: ......!.....!...


[beat_009]

bd: !.......!.......
ch: !.!!!.!.!.!.!.!.
lt: ............!.!.
mt: ......!...!.....
sd: ...!............


[beat_010]

bd: !.....!.!.....!.
ch: !.!!!.!.!.!.!.!.
rs: ....!.....!.....


[beat_011]

bd: !.......!.....!.
ch: !.!!!.!.!.!.!.!.
mt: ..........!.!...
rs: ......!.........


[beat_012]

bd: !.......!.....!.
ch: !.!!!.!.!.!.!.!.
lt: ..............!.
mt: ......!...!.....
rs: ...!............


[break_002]
bd: !...!.!...!.!...
ch: !...!.!...!.!...
mt: ..!!....!!....!!
sd: .!...!.!...!.!..


[break_003]
bd: .............!..
ch: .............!..
lt: ......!.!.!.....
mt: ....!...........
sd: !!..........!...


[break_013]
bd: !...............
ch: !...............
lt: ............!!!!
mt: ......!!!!!.....
sd: .!!!!...........


[break_014]

ch: ............!...
ht: ....!.!.........
lt: ........!.!.....
sd: !..!........!...


[break_015]

lt: ..............!.
mt: ..........!.....
sd: !.!...!.........
