; drum styles. bd-sound from bd.wav file, ch-from ch.wav, etc. ac-step accent not a sound.
; ac-accent, bd-bass drum, cb-cow bell, ch-close hat, cp-clap, cy-cymbals, ht-hi tom
; lt-low tom, mt-mid tom, oh-open hat, rs-rim shot, sd-snare drum
; styles having 'brk' in the name are break/fill styles, others are normal beats


[ptn_001]
ac: ................
bd: !...............
ch: !...............


[ptn_002]
ac: ................
bd: !...............
ch: !!!!!!!!!!!!!!!!


[ptn_003]
ac: ................
bd: !...............
ch: !.......!.......


[ptn_004]
ac: ................
bd: !...............
ch: !...!...!...!...


[ptn_005]
ac: ................
bd: !...............
ch: !.!.!.!.!.!.!.!.
