; drum styles. bd-sound from bd.wav file, ch-from ch.wav, etc. ac-step accent not a sound.
; ac-accent, bd-bass drum, cb-cow bell, ch-close hat, cp-clap, cy-cymbals, ht-hi tom
; lt-low tom, mt-mid tom, oh-open hat, rs-rim shot, sd-snare drum
; styles having 'brk' in the name are break/fill styles, others are normal beats


[beat_001]
ac: ................
bd: !.!..!.!..!!.!..
ch: !.!.!.!.!.!.!.!.
sd: ....!.......!...


[beat_004]
ac: ................
bd: !.......!.......
ch: !!.!!!.!!!.!!!.!
oh: ..!...!...!...!.
sd: ....!.......!..!


[beat_005]
ac: ................
bd: !.!...!...!.....
ch: !.!.!.!.!.!.!.!.
sd: ....!.......!..!


[beat_006]
ac: ................
bd: !.!.....!.!!....
ch: !!!!!!!!!!!!!!!!
sd: ....!..!.!..!..!


[beat_007]
ac: ................
bd: !...!!.!!.!.!!.!
ch: !.!.!.!.!.!.!.!.
sd: ..!...!....!..!.


[beat_008]
ac: ................
bd: !.!.....!.!!....
ch: !.!.!.!.!.!.!.!.
sd: ....!..!.!..!..!


[beat_009]
ac: ................
bd: !.!!....!..!....
ch: !.!!!.!!!.!!!.!!
sd: ....!.!!....!...


[beat_010]
ac: ................
bd: !.!!...!!.!!.!..
ch: !.!.!.!.!.!.!.!.
sd: ....!.......!...


[beat_011]
ac: ................
bd: ...!.!!..!.!.!!.
ch: !.!.!.!.!.!.!.!.
sd: !...!...!...!...


[beat_012]
ac: ................
bd: !..!...!.!.!.!..
ch: !.!.!.!.!.!.!.!.
sd: ....!.......!...


[break_002]
ac: ................
bd: !..!...!.......!
ch: !..!!..!........
ht: ............!!..
lt: .....!..........
sd: ..!.....!.!!..!.


[break_003]
ac: ................
bd: ..!!..!!..!!....
lt: ........!!......
mt: ....!!..........
sd: !!..........!!!!


[break_013]
ac: ................
lt: ....!.....!.....
mt: ..!.....!.......
sd: !!.!.!!!.!.!!!!!


[break_014]
ac: ................
bd: !..!.....!......
ch: ...!......!.....
mt: ......!!!...!.!!
sd: .!!.!.....!.....


[break_015]
ac: ................
bd: !..!...!...!....
ch: ............!...
lt: ........!!!.....
mt: ....!!!.........
sd: .!!.........!...
