; drum styles. bd-sound from bd.wav file, ch-from ch.wav, etc.
; bd-bass drum, cb-cow bell, ch-close hat, cp-clap, cy-cymbals, ht-hi tom
; lt-low tom, mt-mid tom, oh-open hat, rs-rim shot, sd-snare drum
; styles having 'break' in the name are break/fill styles, others are normal beats


[beat_001]

bd: !.!..!.!..!!.!..
ch: !.!.!.!.!.!.!.!.
sd: ....!.......!...


[beat_004]

bd: !.......!.......
ch: !!.!!!.!!!.!!!.!
oh: ..!...!...!...!.
sd: ....!.......!..!


[beat_005]

bd: !.!...!...!.....
ch: !.!.!.!.!.!.!.!.
sd: ....!.......!..!


[beat_006]

bd: !.!.....!.!!....
ch: !!!!!!!!!!!!!!!!
sd: ....!..!.!..!..!


[beat_007]

bd: !...!!.!!.!.!!.!
ch: !.!.!.!.!.!.!.!.
sd: ..!...!....!..!.


[beat_008]

bd: !.!.....!.!!....
ch: !.!.!.!.!.!.!.!.
sd: ....!..!.!..!..!


[beat_009]

bd: !.!!....!..!....
ch: !.!!!.!!!.!!!.!!
sd: ....!.!!....!...


[beat_010]

bd: !.!!...!!.!!.!..
ch: !.!.!.!.!.!.!.!.
sd: ....!.......!...


[beat_011]

bd: ...!.!!..!.!.!!.
ch: !.!.!.!.!.!.!.!.
sd: !...!...!...!...


[beat_012]

bd: !..!...!.!.!.!..
ch: !.!.!.!.!.!.!.!.
sd: ....!.......!...


[break_002]

bd: !..!...!.......!
ch: !..!!..!........
ht: ............!!..
lt: .....!..........
sd: ..!.....!.!!..!.


[break_003]

bd: ..!!..!!..!!....
lt: ........!!......
mt: ....!!..........
sd: !!..........!!!!


[break_013]

lt: ....!.....!.....
mt: ..!.....!.......
sd: !!.!.!!!.!.!!!!!


[break_014]

bd: !..!.....!......
ch: ...!......!.....
mt: ......!!!...!.!!
sd: .!!.!.....!.....


[break_015]

bd: !..!...!...!....
ch: ............!...
lt: ........!!!.....
mt: ....!!!.........
sd: .!!.........!...
