; drum styles. bd-sound from bd.wav file, ch-from ch.wav, etc. ac-step accent not a sound.
; ac-accent, bd-bass drum, cb-cow bell, ch-close hat, cp-clap, cy-cymbals, ht-hi tom
; lt-low tom, mt-mid tom, oh-open hat, rs-rim shot, sd-snare drum
; styles having 'brk' in the name are break/fill styles, others are normal beats


[brk_001]
ac: ..............!.
ch: ..............!.
lt: ..........!!!...
mt: ......!!!.......
sd: !.!!!.........!.


[brk_002]
ac: ................
lt: ....!.....!.....
mt: !..!..!..!..!..!
sd: .!!....!!....!!.


[brk_003]
ac: ................
bd: !..!!..!!..!!..!
ch: !!....!!..!.!...
ht: ..!.!...........
lt: ...........!..!.
mt: ........!.......
oh: ...............!
sd: ..!.!...!..!..!.


[ptn_004]
ac: ................
bd: !..!!..!!..!!..!
cb: !...!...!...!...
ch: .!!..!!..!!..!!.
lt: .......!.......!
mt: ...!............
sd: ...........!....


[ptn_005]
ac: ................
bd: !..!!..!!..!!..!
cb: !.!.!!.!.!!.!!.!
ch: .!.!..!.!.....!.
mt: ...........!....


[ptn_006]
ac: ................
bd: !..!!..!!..!!..!
ch: !.!!!.!!!.!!!.!!
lt: ..............!!
rs: ..!..!..!.......
sd: ...........!....


[ptn_007]
ac: ................
bd: !..!!..!!..!!..!
ch: !.!!!.!!!.!!!.!!
lt: ...............!
mt: .......!........
rs: .!...!...!...!..
sd: ...!.......!....


[ptn_008]
ac: !...!...!...!...
bd: !..!!..!!..!!..!
ch: !!!!!!!!!!!!!!!!
sd: ....!.......!...


[ptn_009]
ac: .......!...!....
bd: !..!!..!!..!!..!
ch: .!.!..!.!..!..!.
sd: !.!.!!.!.!!.!!.!
