; drum styles. bd-sound from bd.wav file, ch-from ch.wav, etc.
; bd-bass drum, cb-cow bell, ch-close hat, cp-clap, cy-cymbals, ht-hi tom
; lt-low tom, mt-mid tom, oh-open hat, rs-rim shot, sd-snare drum
; styles having 'break' in the name are break/fill styles, others are normal beats


[beat_001]
bd: !..!!..!!..!!..!
ch: .!.!..!.!..!..!.
sd: !.!.!!.!.!!.!!.!


[beat_003]
bd: !..!!..!!..!!..!
ch: !!!!!!!!!!!!!!!!
sd: ....!.......!...


[beat_004]
bd: !..!!..!!..!!..!
cb: !.!.!!.!.!!.!!.!
ch: .!.!..!.!.....!.
mt: ...........!....


[beat_005]
bd: !..!!..!!..!!..!
cb: !...!...!...!...
ch: .!!..!!..!!..!!.
lt: .......!.......!
mt: ...!............
sd: ...........!....


[beat_006]
bd: !..!!..!!..!!..!
ch: !.!!!.!!!.!!!.!!
lt: ..............!!
rs: ..!..!..!.......
sd: ...........!....


[beat_007]
bd: !..!!..!!..!!..!
ch: !.!!!.!!!.!!!.!!
lt: ...............!
mt: .......!........
rs: .!...!...!...!..
sd: ...!.......!....


[break_002]
ch: ..............!.
lt: ..........!!!...
mt: ......!!!.......
sd: !.!!!.........!.


[break_008]
lt: ....!.....!.....
mt: !..!..!..!..!..!
sd: .!!....!!....!!.


[break_009]
bd: !..!!..!!..!!..!
ch: !!....!!..!.!...
ht: ..!.!...........
lt: ...........!..!.
mt: ........!.......
oh: ...............!
sd: ..!.!...!..!..!.
