; drum styles. bd-sound from bd.wav file, ch-from ch.wav, etc.
; bd-bass drum, cb-cow bell, ch-close hat, cp-clap, cy-cymbals, ht-hi tom
; lt-low tom, mt-mid tom, oh-open hat, rs-rim shot, sd-snare drum
; styles having 'break' in the name are break/fill styles, others are normal beats


[beat_001]

bd: !.!..!!.!..!
cy: !..!..!..!..
sd: ...!.....!..


[beat_003]

bd: !....!!.!..!
cy: !..!..!..!.!
sd: ...!.....!..


[beat_004]

bd: !..!..!..!..
ch: !..!..!..!..
sd: ...!.....!..


[beat_005]

bd: !..!..!..!..
ch: !..!..!..!..


[beat_006]

bd: !..!..!..!..
ch: !..!.!!..!.!
sd: ...!.....!..


[beat_007]

bd: !..!.!!..!..
ch: !..!.!!..!.!
sd: ...!.....!..


[break_002]

bd: !..!........
ch: !..!........
sd: ......!!!!!!


[break_008]

bd: !!!.!!!.!...
ch: ..........!.
sd: ...!...!.!!.


[break_009]

bd: !..!..!..!..
mt: ....!!....!!
oh: !..!..!..!..
sd: .!!....!!...
