
[Afro1A 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
rs: ......8...!...!.
bd: !.......8.......
[Afro1B 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
rs: ......8.....!...
bd: !.......!.!...!.
[Afro1Brk 4/4]
#...1234567890123456
ac: ....!.......!..!
ch: !...............
mt: ......!!!!!.....
sd: .!!!!...........
lt: ............!!!!
bd: !...............
[Afro2A 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ..........8.....
rs: ...!..!.........
lt: ............!.!.
bd: !.......8.......
[Afro2B 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ..........!.!...
rs: ......8.........
bd: !.......8.....!.
[Afro2Brk 4/4]
#...1234567890123456
ac: ............!!..
ch: .............8..
mt: ....8...........
sd: !!..........8...
lt: ......!.!.!.....
bd: .............8..
[Afro3A 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ......8...!.....
rs: ...!............
lt: ..............!.
bd: !.......8.....!.
[Afro3B 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ......8...!.....
sd: ...!............
lt: ............!.!.
bd: !.......8.......
[Afro3Brk 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !...!.!...!.!...
mt: ..!!....!!....!!
sd: .!...!.!...!.!..
bd: !...!.!...!.!...
[Afro4A 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
rs: ......8.....!...
bd: !.......!.!...!.
[Afro4B 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ..........8.....
rs: ......8.........
lt: ..............!.
bd: !.......8.......
[Afro4Brk 4/4]
#...1234567890123456
ac: ............!...
ch: ............8...
ht: ....!.!.........
sd: !..!........8...
lt: ........!.!.....
[Afro5A 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
ht: ..........8.....
rs: ......8.........
lt: ..............!.
bd: !.......8.......
[Afro5B 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
rs: ....8.....!.....
bd: !.....!.!.....!.
[Afro5Brk 4/4]
#...1234567890123456
mt: ..........8.....
sd: !.!...!.........
lt: ..............!.

