
[Funk1A 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !..!......8..!..
[Funk1B 4/4]
#...1234567890123456
ch: !.8.8.!.8.8.!...
oh: ..............!.
sd: ....8.......8...
bd: !!.....8..!..!..
[Funk1Brk 4/4]
#...1234567890123456
ac: !..!........!.!!
ch: !..!..!..!..!...
sd: .!!.!!.!!.!!..!!
bd: !..!..!..!..!...
[Funk2A 4/4]
#...1234567890123456
ch: !.8.8!!......8..
oh: .......!.8.8....
sd: ....8.......8...
bd: !......!.8.8.!..
[Funk2B 4/4]
#...1234567890123456
ch: !.888.!!!.888.!!
sd: ...........8....
bd: !.!..!..!.......
[Funk2Brk 4/4]
#...1234567890123456
ac: .............!..
ch: !...!.8.8....8..
sd: ...!......888...
bd: !...!.8.8....8..
[Funk3A 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !!8!8!8!8!!!!!!!
bd: !......!!.......
[Funk3B 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !!8!8!8!8!!!!!!!
bd: !.!..!..!.......
[Funk3Brk 4/4]
#...1234567890123456
ac: ...!........!.!.
ch: !......8......!.
sd: .!!!!!!..!!!!.!.
bd: !......8........
[Funk4A 4/4]
#...1234567890123456
ch: !.8.8!!!..!.888.
sd: ....8.......8...
bd: !.!....8..!.....
[Funk4B 4/4]
#...1234567890123456
ch: !.8.8!!.8.8.!.!.
sd: ....8......8....
bd: !.!.....8.......
[Funk4Brk 4/4]
#...1234567890123456
ht: ....!!!!........
sd: !!!!....!!!!!!..
bd: .............8..
[Funk5A 4/4]
#...1234567890123456
ac: .....!......!...
ch: !.8.8.!.8.8.!.!.
sd: ....!!.....!!...
bd: !.!.....8.......
[Funk5B 4/4]
#...1234567890123456
ch: !.8.8!!.8.8!!.!!
sd: ....8..!....8...
bd: ..!..!..!..!....
[Funk5Brk 4/4]
#...1234567890123456
ch: !.!..!..........
ht: ........!!!!....
sd: ....8.......!!!!
bd: !.!..!..........
[Funk6A 4/4]
#...1234567890123456
ac: ....!!......!!..
ch: 88.!..!.88.!..!.
sd: ..!.88.!..!.!!.!
bd: !..!..!.!..!..!.
[Funk6B 4/4]
#...1234567890123456
ac: ....!!......!!..
ch: 88.!..!.88.!..!.
ht: ..!.......8.....
sd: ....!!......!!..
lt: .......8.......!
bd: !..!..!.!..!..!.
[Funk6Brk 4/4]
#...1234567890123456
mt: ......888.......
sd: ....8........!!.
lt: ..........!!....
[Funk7A 4/4]
#...1234567890123456
ch: !!!..!!.888..!!.
oh: ...!...!...!...!
sd: ....8.......8...
bd: !..!...!.......!
[Funk7B 4/4]
#...1234567890123456
ch: !!!..!!.888..!!.
oh: ...!...!...!...!
mt: ............8...
sd: ....8...........
bd: !!.....8..!..!..
[Funk7Brk 4/4]
#...1234567890123456
ac: ......!........!
ch: ....!.!.........
sd: !..!.....!.!!!!!
bd: .!..!.!.........
[Funk8A 4/4]
#...1234567890123456
oh: !...!...!...!...
sd: ......8.......!.
bd: !..!....!.!!....
[Funk8B 4/4]
#...1234567890123456
oh: !...!...!...!...
sd: ......8.......!!
bd: !..!....!.!!....
[Funk8Brk 4/4]
#...1234567890123456
ac: .....!...!..!.!.
ch: ............!.!.
mt: .....8...!......
sd: !.8.8..!!.......
bd: ...........!!.!.
[Funk9A 4/4]
#...1234567890123456
ch: ....888.!!!.!!!!
oh: ..!.............
sd: ....8.......8...
bd: !.......!.!....!
[Funk9B 4/4]
#...1234567890123456
ch: !.888........8..
oh: .....!.8.8.!....
sd: ....8.......8...
bd: !.!!.8.8.!.!.!..
[Funk9Brk 4/4]
#...1234567890123456
ac: ....!.......!...
ch: ............8...
sd: .88.!..!....8...
bd: !..!.!...!.!....
[Funk10A 4/4]
#...1234567890123456
ch: !!!!.!!!!!!!.!!!
sd: ....8.......8...
bd: !.!....8........
[Funk10B 4/4]
#...1234567890123456
ch: !!!!.!!!!!!!.!!!
sd: ....8.......8...
bd: ..!..!..!.......
[Funk10Brk 4/4]
#...1234567890123456
ac: .!...!....!.....
ch: .....8....!.....
sd: !!.!!..!!...!!!!
bd: .....8....!.....
[Funk11A 4/4]
#...1234567890123456
ac: ............!...
ch: !.888.8.8.!.8.8.
sd: ....8.......8...
bd: !..!..!.!..!....
[Funk11B 4/4]
#...1234567890123456
ac: ............!...
ch: !.888.8.8.!.!.!.
sd: ....8.......8...
bd: !!....!.!..!....
[Funk11Brk 4/4]
#...1234567890123456
ac: ...!...!...!...!
ht: .....!!....8....
sd: ..888...888...!!
lt: !......8....!...
[Funk12A 4/4]
#...1234567890123456
ch: !!!..!!.8.8..!!.
oh: ...!...!.8.8...!
sd: ....8.......8...
bd: !..!...!.8.8...!
[Funk12B 4/4]
#...1234567890123456
ch: !!!..!!.888..!!.
oh: ...!...!...!...!
sd: ....8.......8...
bd: !..!...!...!....
[Funk12Brk 4/4]
#...1234567890123456
oh: !.!.............
mt: ........!!!!....
sd: .!.!!!!!........
lt: ............!!!!
[Funk13A 4/4]
#...1234567890123456
ch: !!!.!!..888.!!..
oh: ......8.......!.
sd: ............!.!.
bd: !..!..!....8....
[Funk13B 4/4]
#...1234567890123456
ch: !!!.!!..888.!!..
oh: ......8.......!.
sd: ............!.!!
bd: !..!..!....8....
[Funk13Brk 4/4]
#...1234567890123456
mt: .....!!......!.!
sd: ...!!....!.!!...
bd: !...............
[Funk14A 4/4]
#...1234567890123456
ch: !.8.8.!.8.8.!.!.
sd: ....8.......8...
bd: !!....!!..!..!..
[Funk14B 4/4]
#...1234567890123456
ch: !.8.8.!.8.8.!.!.
sd: ....8.......8...
bd: !..!....!!......
[Funk14Brk 4/4]
#...1234567890123456
ac: .............!..
ch: .............8..
sd: !..!!...!.!.!!..
bd: .....8.......8..
 