
[Funk1MeasureA 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !..!......8..!..
[Funk1MeasureB 4/4]
#...1234567890123456
ch: !.8.8.!.8.8.!...
oh: ..............!.
sd: ....8.......8...
bd: !!.....8..!..!..
[Funk1Break 4/4]
#...1234567890123456
ac: !..!........!.!!
ch: !..!..!..!..!...
sd: .!!.!!.!!.!!..!!
bd: !..!..!..!..!...
[Funk2MeasureA 4/4]
#...1234567890123456
ch: !.8.8!!......8..
oh: .......!.8.8....
sd: ....8.......8...
bd: !......!.8.8.!..
[Funk2MeasureB 4/4]
#...1234567890123456
ch: !.888.!!!.888.!!
sd: ...........8....
bd: !.!..!..!.......
[Funk2Break 4/4]
#...1234567890123456
ac: .............!..
ch: !...!.8.8....8..
sd: ...!......888...
bd: !...!.8.8....8..
[Funk3MeasureA 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !!8!8!8!8!!!!!!!
bd: !......!!.......
[Funk3MeasureB 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !!8!8!8!8!!!!!!!
bd: !.!..!..!.......
[Funk3Break 4/4]
#...1234567890123456
ac: ...!........!.!.
ch: !......8......!.
sd: .!!!!!!..!!!!.!.
bd: !......8........
[Funk4MeasureA 4/4]
#...1234567890123456
ch: !.8.8!!!..!.888.
sd: ....8.......8...
bd: !.!....8..!.....
[Funk4MeasureB 4/4]
#...1234567890123456
ch: !.8.8!!.8.8.!.!.
sd: ....8......8....
bd: !.!.....8.......
[Funk4Break 4/4]
#...1234567890123456
ht: ....!!!!........
sd: !!!!....!!!!!!..
bd: .............8..
[Funk5MeasureA 4/4]
#...1234567890123456
ac: .....!......!...
ch: !.8.8.!.8.8.!.!.
sd: ....!!.....!!...
bd: !.!.....8.......
[Funk5MeasureB 4/4]
#...1234567890123456
ch: !.8.8!!.8.8!!.!!
sd: ....8..!....8...
bd: ..!..!..!..!....
[Funk5Break 4/4]
#...1234567890123456
ch: !.!..!..........
ht: ........!!!!....
sd: ....8.......!!!!
bd: !.!..!..........
[Funk6MeasureA 4/4]
#...1234567890123456
ac: ....!!......!!..
ch: 88.!..!.88.!..!.
sd: ..!.88.!..!.!!.!
bd: !..!..!.!..!..!.
[Funk6MeasureB 4/4]
#...1234567890123456
ac: ....!!......!!..
ch: 88.!..!.88.!..!.
ht: ..!.......8.....
sd: ....!!......!!..
lt: .......8.......!
bd: !..!..!.!..!..!.
[Funk6Break 4/4]
#...1234567890123456
mt: ......888.......
sd: ....8........!!.
lt: ..........!!....
[Funk7MeasureA 4/4]
#...1234567890123456
ch: !!!..!!.888..!!.
oh: ...!...!...!...!
sd: ....8.......8...
bd: !..!...!.......!
[Funk7MeasureB 4/4]
#...1234567890123456
ch: !!!..!!.888..!!.
oh: ...!...!...!...!
mt: ............8...
sd: ....8...........
bd: !!.....8..!..!..
[Funk7Break 4/4]
#...1234567890123456
ac: ......!........!
ch: ....!.!.........
sd: !..!.....!.!!!!!
bd: .!..!.!.........
[Funk8MeasureA 4/4]
#...1234567890123456
oh: !...!...!...!...
sd: ......8.......!.
bd: !..!....!.!!....
[Funk8MeasureB 4/4]
#...1234567890123456
oh: !...!...!...!...
sd: ......8.......!!
bd: !..!....!.!!....
[Funk8Break 4/4]
#...1234567890123456
ac: .....!...!..!.!.
ch: ............!.!.
mt: .....8...!......
sd: !.8.8..!!.......
bd: ...........!!.!.
[Funk9MeasureA 4/4]
#...1234567890123456
ch: ....888.!!!.!!!!
oh: ..!.............
sd: ....8.......8...
bd: !.......!.!....!
[Funk9MeasureB 4/4]
#...1234567890123456
ch: !.888........8..
oh: .....!.8.8.!....
sd: ....8.......8...
bd: !.!!.8.8.!.!.!..
[Funk9Break 4/4]
#...1234567890123456
ac: ....!.......!...
ch: ............8...
sd: .88.!..!....8...
bd: !..!.!...!.!....
[Funk10MeasureA 4/4]
#...1234567890123456
ch: !!!!.!!!!!!!.!!!
sd: ....8.......8...
bd: !.!....8........
[Funk10MeasureB 4/4]
#...1234567890123456
ch: !!!!.!!!!!!!.!!!
sd: ....8.......8...
bd: ..!..!..!.......
[Funk10Break 4/4]
#...1234567890123456
ac: .!...!....!.....
ch: .....8....!.....
sd: !!.!!..!!...!!!!
bd: .....8....!.....
[Funk11MeasureA 4/4]
#...1234567890123456
ac: ............!...
ch: !.888.8.8.!.8.8.
sd: ....8.......8...
bd: !..!..!.!..!....
[Funk11MeasureB 4/4]
#...1234567890123456
ac: ............!...
ch: !.888.8.8.!.!.!.
sd: ....8.......8...
bd: !!....!.!..!....
[Funk11Break 4/4]
#...1234567890123456
ac: ...!...!...!...!
ht: .....!!....8....
sd: ..888...888...!!
lt: !......8....!...
[Funk12MeasureA 4/4]
#...1234567890123456
ch: !!!..!!.8.8..!!.
oh: ...!...!.8.8...!
sd: ....8.......8...
bd: !..!...!.8.8...!
[Funk12MeasureB 4/4]
#...1234567890123456
ch: !!!..!!.888..!!.
oh: ...!...!...!...!
sd: ....8.......8...
bd: !..!...!...!....
[Funk12Break 4/4]
#...1234567890123456
oh: !.!.............
mt: ........!!!!....
sd: .!.!!!!!........
lt: ............!!!!
[Funk13MeasureA 4/4]
#...1234567890123456
ch: !!!.!!..888.!!..
oh: ......8.......!.
sd: ............!.!.
bd: !..!..!....8....
[Funk13MeasureB 4/4]
#...1234567890123456
ch: !!!.!!..888.!!..
oh: ......8.......!.
sd: ............!.!!
bd: !..!..!....8....
[Funk13Break 4/4]
#...1234567890123456
mt: .....!!......!.!
sd: ...!!....!.!!...
bd: !...............
[Funk14MeasureA 4/4]
#...1234567890123456
ch: !.8.8.!.8.8.!.!.
sd: ....8.......8...
bd: !!....!!..!..!..
[Funk14MeasureB 4/4]
#...1234567890123456
ch: !.8.8.!.8.8.!.!.
sd: ....8.......8...
bd: !..!....!!......
[Funk14Break 4/4]
#...1234567890123456
ac: .............!..
ch: .............8..
sd: !..!!...!.!.!!..
bd: .....8.......8..
 