
[Pop1A 4/4]
#...1234567890123456
ac: ....!.......!...
ch: !.!.!.!.!.!.!.!.
sd: ....!.!.....8...
bd: !.......8.....!.
[Pop1B 4/4]
#...1234567890123456
ac: ....!...........
ch: !.!.!.!.!.!.!.!.
sd: ....8.....!.....
bd: !.....!.!.....!.
[Pop1Brk 4/4]
#...1234567890123456
ac: ............!...
ch: !...............
sd: ..!.!.!.!.888...
lt: ..!.!.!.!.......
bd: !...............
[Pop2A 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ...!....8...!...
bd: !.....8...!..!..
[Pop2B 4/4]
#...1234567890123456
ac: .............!..
ch: !...!...!...!...
sd: ...!......8..!..
bd: !.....8.....!...
[Pop2Brk 4/4]
#...1234567890123456
ac: ...!.....!......
mt: ........!!......
sd: ..!!........!!!!
bd: !...!.!...!.....
[Pop3A 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: !..!....8..!....
bd: ....!.88.!..!...
[Pop3B 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8.......8...
bd: !.88.!..!.88.!..
[Pop3Brk 4/4]
#...1234567890123456
ac: ...........!....
ch: ............8...
mt: ...!............
sd: !.........!!....
lt: ................
bd: ............8...
[Pop4A 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8..!....8...
bd: !.......!.!.....
[Pop4B 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8..!....8...
bd: !.!.....!.!!....
[Pop4Brk 4/4]
#...1234567890123456
ac: !...........!..!
ch: !...............
sd: ....!.!.!...!.!!
bd: !.........8.....
[Pop5A 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ...!!.......8...
bd: !.....8...!..!..
[Pop5B 4/4]
#...1234567890123456
ac: .............!..
ch: !...!...!...!!..
sd: ...!......!.!...
bd: !.....8......8..
[Pop5Brk 4/4]
#...1234567890123456
oh: !...!...!...!...
sd: .!!!!.!!!!!.!!!!
bd: !...!...!...!...