
[Rhythm&Blues1A 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8..!
bd: !.!...!...!.....
[Rhythm&Blues1B 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8..!.!..!..!
bd: !.!.....!.!!....
[Rhythm&Blues1Brk 4/4]
#...1234567890123456
mt: ..!.....8.......
sd: !!.!.888.!.!!!!!
lt: ....8.....!.....
[Rhythm&Blues2A 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !.!..!.!..88.!..
[Rhythm&Blues2B 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: !...!...!...!...
bd: ...!.!!..!.!.!!.
[Rhythm&Blues2Brk 4/4]
#...1234567890123456
mt: ....!!..........
sd: !!..........!!!!
lt: ........!!......
bd: ..!!..!!..!!....
[Rhythm&Blues3A 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !..!...!.!.!.!..
[Rhythm&Blues3B 4/4]
#...1234567890123456
ch: !.888.!!!.888.!!
sd: ....!.!!....8...
bd: !.!!....8..!....
[Rhythm&Blues3Brk 4/4]
#...1234567890123456
ch: !..!!..!........
ht: ............!!..
sd: ..!.....!.!!..!.
lt: .....8..........
bd: !..!...!.......!
[Rhythm&Blues4A 4/4]
#...1234567890123456
ch: !!8!8!8!8!!!!!!!
sd: ....8..!.!..!..!
bd: !.!.....!.!!....
[Rhythm&Blues4B 4/4]
#...1234567890123456
ch: !!.888.!!!.888.!
oh: ..!...!...!...!.
sd: ....8.......8..!
bd: !.......8.......
[Rhythm&Blues4Brk 4/4]
#...1234567890123456
ch: ...!......8.....
mt: ......888...!.!!
sd: .88.!.....8.....
bd: !..!.....8......
[Rhythm&Blues5A 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ..!...!....8..!.
bd: !...!!.!!.!.!!.!
[Rhythm&Blues5B 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !.!!...!!.88.!..
[Rhythm&Blues5Brk 4/4]
#...1234567890123456
ch: ............8...
mt: ....888.........
sd: .!!.........8...
lt: ........888.....
bd: !..!...!...!....