[Rock1MeasureA 4/4]
#...1234567890123456
ac: ....!.......!...
ch: !...!...!...!...
sd: ....8.......8...
bd: !.....!.!.......
[Rock1MeasureB 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8.......8...
bd: !.....!.!.!...!.
[Rock1Break 4/4]
#...1234567890123456
ac: !...........!..!
ch: !...............
ht: ...!!..!!..!....
sd: ..!...!...!.!!!!
bd: !...............
[Rock2MeasureA 4/4]
#...1234567890123456
ac: !.!.!.!.!.!.!.!.
ch: !!8!8!8!8!!!!!!.
oh: ...............!
sd: ....8.......8...
bd: !.!..!..!......!
[Rock2MeasureB 4/4]
#...1234567890123456
ch: !!!!!!!.!!!!!!!.
oh: .......8.......!
sd: ....8.......!.!.
bd: !.!..!..!......!
[Rock2Break 4/4]
#...1234567890123456
cy: ............!.!.
mt: ....!!!!........
sd: !!!!............
lt: ........!!!!....
bd: !.!..!..!.!.!.!.
[Rock3MeasureA 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !.........8...!.
[Rock3MeasureB 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !.......!.!.....
[Rock3Break 4/4]
#...1234567890123456
ch: !...!...!...!...
oh: ..!...!...!...!.
sd: ..!...!.....8...
bd: !.......!.!.....
[Rock4MeasureA 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !...!...!...!...
[Rock4MeasureB 4/4]
#...1234567890123456
ac: ....!.......!...
ch: !.!.!.!.!.!.!.!.
sd: !...!...!...!...
bd: !...!...!...!...
[Rock4Break 4/4]
#...1234567890123456
ac: !..!!..!!..!!..!
sd: !!8!8!8!8!!!!!!!
bd: !...!...!...!...
[Rock5MeasureA 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8.......8...
bd: !.......!.!.....
[Rock5MeasureB 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8.......8...
bd: !.....!.!.......
[Rock5Break 4/4]
#...1234567890123456
ac: .......!..!.!...
ch: !...............
sd: ....8..!..!.!...
bd: !...............