[Rock1A 4/4]
#...1234567890123456
ac: ....!.......!...
ch: !...!...!...!...
sd: ....8.......8...
bd: !.....!.!.......
[Rock1B 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8.......8...
bd: !.....!.!.!...!.
[Rock1Brk 4/4]
#...1234567890123456
ac: !...........!..!
ch: !...............
ht: ...!!..!!..!....
sd: ..!...!...!.!!!!
bd: !...............
[Rock2A 4/4]
#...1234567890123456
ac: !.!.!.!.!.!.!.!.
ch: !!8!8!8!8!!!!!!.
oh: ...............!
sd: ....8.......8...
bd: !.!..!..!......!
[Rock2B 4/4]
#...1234567890123456
ch: !!!!!!!.!!!!!!!.
oh: .......8.......!
sd: ....8.......!.!.
bd: !.!..!..!......!
[Rock2Brk 4/4]
#...1234567890123456
cy: ............!.!.
mt: ....!!!!........
sd: !!!!............
lt: ........!!!!....
bd: !.!..!..!.!.!.!.
[Rock3A 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !.........8...!.
[Rock3B 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !.......!.!.....
[Rock3Brk 4/4]
#...1234567890123456
ch: !...!...!...!...
oh: ..!...!...!...!.
sd: ..!...!.....8...
bd: !.......!.!.....
[Rock4A 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !...!...!...!...
[Rock4B 4/4]
#...1234567890123456
ac: ....!.......!...
ch: !.!.!.!.!.!.!.!.
sd: !...!...!...!...
bd: !...!...!...!...
[Rock4Brk 4/4]
#...1234567890123456
ac: !..!!..!!..!!..!
sd: !!8!8!8!8!!!!!!!
bd: !...!...!...!...
[Rock5A 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8.......8...
bd: !.......!.!.....
[Rock5B 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8.......8...
bd: !.....!.!.......
[Rock5Brk 4/4]
#...1234567890123456
ac: .......!..!.!...
ch: !...............
sd: ....8..!..!.!...
bd: !...............