
[Afro-Cuban1MeasureA 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
rs: ......8...!...!.
bd: !.......8.......
[Afro-Cuban1MeasureB 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
rs: ......8.....!...
bd: !.......!.!...!.
[Afro-Cuban1Break 4/4]
#...1234567890123456
ac: ....8.......8..!
ch: !...............
mt: ......!!!!!.....
sd: .!!!!...........
lt: ............!!!!
bd: !...............
[Afro-Cuban2MeasureA 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ..........8.....
rs: ...!..!.........
lt: ............!.!.
bd: !.......8.......
[Afro-Cuban2MeasureB 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ..........!.!...
rs: ......8.........
bd: !.......8.....!.
[Afro-Cuban2Break 4/4]
#...1234567890123456
ac: ............!!..
ch: .............8..
mt: ....8...........
sd: !!..........8...
lt: ......!.!.!.....
bd: .............8..
[Afro-Cuban3MeasureA 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ......8...!.....
rs: ...!............
lt: ..............!.
bd: !.......8.....!.
[Afro-Cuban3MeasureB 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ......8...!.....
sd: ...!............
lt: ............!.!.
bd: !.......8.......
[Afro-Cuban3Break 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !...!.!...!.!...
mt: ..!!....!!....!!
sd: .!...!.!...!.!..
bd: !...!.!...!.!...
[Afro-Cuban4MeasureA 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
rs: ......8.....!...
bd: !.......!.!...!.
[Afro-Cuban4MeasureB 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
mt: ..........8.....
rs: ......8.........
lt: ..............!.
bd: !.......8.......
[Afro-Cuban4Break 4/4]
#...1234567890123456
ac: ............8...
ch: ............8...
ht: ....!.!.........
sd: !..!........8...
lt: ........!.!.....
[Afro-Cuban5MeasureA 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
ht: ..........8.....
rs: ......8.........
lt: ..............!.
bd: !.......8.......
[Afro-Cuban5MeasureB 4/4]
#...1234567890123456
ch: !.888.!.!.!.!.!.
rs: ....8.....!.....
bd: !.....!.!.....!.
[Afro-Cuban5Break 4/4]
#...1234567890123456
mt: ..........8.....
sd: !.!...!.........
lt: ..............!.

