
[Ballad1MeasureA 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !.....!.!.......
[Ballad1MeasureB 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !......!!.......
[Ballad1Break 4/4]
#...1234567890123456
ac: ...............!
ch: !.!.............
mt: ........888.....
sd: ....!.!!........
lt: ............!!!!
bd: !...............
[Ballad2MeasureA 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!!..
oh: ..............!.
sd: ....8.......8...
bd: !......88.!.....
[Ballad2MeasureB 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !!.....88.!..!..
[Ballad2Break 4/4]
#...1234567890123456
ac: ....8.......8...
ch: !...............
mt: ........!.!.....
sd: ..888.!.........
lt: ............!!!!
bd: !.......8.......
[Ballad3MeasureA 4/4]
#...1234567890123456
ch: !...!...!...!...
oh: ..!...!...!..!..
sd: ........8.....!!
bd: !.....8.........
[Ballad3MeasureB 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !!....!!........
[Ballad3Break 4/4]
#...1234567890123456
ht: ......!!........
sd: ..!!..........!!
lt: ..........!!....
bd: !...!!..!!..!!..
[Ballad4MeasureA 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !.......!.!...!.
[Ballad4MeasureB 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !.!.!.!.!.!.!.!.
sd: ....8.......8...
bd: !.....!.!.....!.
[Ballad4Break 4/4]
#...1234567890123456
ac: .....8.......8..
ch: .....8..!.......
mt: .!!.......!.!!..
sd: ...!!...........
lt: ................
bd: !....8..!.......
[Ballad5MeasureA 4/4]
#...1234567890123456
ch: !!!!!!!.!!!!!!!.
oh: .......8.......!
sd: ....8.......8...
bd: !.........8....!
[Ballad5MeasureB 4/4]
#...1234567890123456
ch: !!8!8!8!8!!!!!!!
sd: ....8.......8...
bd: !!.....8..!..!..
[Ballad5Break 4/4]
#...1234567890123456
ch: !!!!!!!.........
oh: .......8........
ht: ............!!..
mt: ..........!!....
sd: ....8...!!......
lt: ..............!!
bd: !...............