





[Blues1MeasureA 12/8]
#...123456789012
ch: !!8!8!8!8!!!
sd: ...!.....8..
bd: !.!..!!.!.!!
[Blues1MeasureB 12/8]
#...123456789012
ch: !!8!8!8!8!!!
sd: ...!.....8..
bd: !.!..!!.!.!.
[Blues1Break 12/8]
#...123456789012
ch: !!!!!!!!!...
sd: !!8!8!8!8!!!
bd: !!!!!!!!!...
[Blues2MeasureA 12/8]
#...123456789012
ch: !.!!.!!.!!.!
sd: ...!.....8..
bd: !.!.!.!.!.!.
[Blues2MeasureB 12/8]
#...123456789012
ch: !!8!8!8!8!!!
sd: ...!.....8..
bd: !.!..88.!..!
[Blues2Break 12/8]
#...123456789012
ch: !..!..!..!..
sd: .!!.!!.!!.!!
bd: !..!..!..!..