
[Disco1MeasureA 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !!8!8!8!8!!!!!!!
sd: ....8.......8...
bd: !...!...!...!...
[Disco1MeasureB 4/4]
#...1234567890123456
ch: !!.888.!!.!!!!.!
oh: ..!...!..!....!.
sd: ....8......!!...
bd: !...!...!...!...
[Disco1Break 4/4]
#...1234567890123456
ac: ....8...!...!...
ch: 88.!............
oh: ..!.............
mt: ......8.........
sd: ....!!.!.!!!!!..
lt: ........8.......
bd: !...!...!...!...
[Disco2MeasureA 4/4]
#...1234567890123456
ch: ..!...!...!...!.
sd: ....8.......8...
cb: !...!...!...!...
bd: !...!...!...!...
[Disco2MeasureB 4/4]
#...1234567890123456
ch: !.!!..!!..!!..!!
sd: ....8.......8...
cb: !...!...!...!...
bd: !...!...!...!...
[Disco2Break 4/4]
#...1234567890123456
ch: !!!.............
sd: ...!!.!.!.!.888.
bd: !...!...!...!...
[Disco3MeasureA 4/4]
#...1234567890123456
ch: ..!!..!!..!!..!!
sd: ....8.......8...
bd: !...!...!...!...
[Disco3MeasureB 4/4]
#...1234567890123456
ch: !.888.!!!.888.!!
sd: ....8.......8...
bd: !...!...!...!...
[Disco3Break 4/4]
#...1234567890123456
ch: !!!!............
mt: ........8..!....
sd: ....!.!!.!!.....
cb: ............!.!!
bd: !...!...!...!...
[Disco4MeasureA 4/4]
#...1234567890123456
ch: !!!..!!.888..!!.
oh: ...!...!...!...!
sd: ....8.......8...
bd: !...!...!...!...
[Disco4MeasureB 4/4]
#...1234567890123456
ch: !!!..!!.888..!!.
oh: ...!...!.......!
sd: ....8......!!...
bd: !...!...!..!!...
[Disco4Break 4/4]
#...1234567890123456
ch: !!...!...!...!..
oh: ..!...!...!...!.
sd: ...!!..!!..!!..!
bd: !...!...!...!...
[Disco5MeasureA 4/4]
#...1234567890123456
ch: !!...!.888...!.!
oh: ..!!..!...!!..!.
sd: ....8.......8...
bd: !...!...!...!...
[Disco5MeasureB 4/4]
#...1234567890123456
ch: !!!..!!!!!!!.!!.
oh: ...!...........!
sd: ....8.......8...
bd: !...!...!...!...
[Disco5Break 4/4]
#...1234567890123456
ch: !!..............
oh: ..!!............
mt: ........!!!!....
sd: ....!!!!........
lt: ............!!!!
bd: !...!...!...!...