

[Samba1MeasureA 4/4]
#...1234567890123456
ch: .!!..!!..!!..!!.
mt: ...!............
sd: ...........8....
lt: .......8.......!
cb: !...!...!...!...
bd: !..!!..!!..!!..!
[Samba1MeasureB 4/4]
#...1234567890123456
ch: .!.!..!.!.....!.
mt: ...........8....
cb: !.!.!!.!.!!.!!.!
bd: !..!!..!!..!!..!
[Samba1Break 4/4]
#...1234567890123456
ac: ..............!.
ch: ..............!.
mt: ......888.......
sd: !.888.........!.
lt: ..........888...
[Samba2MeasureA 4/4]
#...1234567890123456
ch: !.888.!!!.888.!!
sd: ...........8....
rs: ..!..!..!.......
lt: ..............!!
bd: !..!!..!!..!!..!
[Samba2MeasureB 4/4]
#...1234567890123456
ch: !.888.!!!.888.!!
mt: .......8........
sd: ...!.......8....
rs: .!...!...!...!..
lt: ...............!
bd: !..!!..!!..!!..!
[Samba2Break 4/4]
#...1234567890123456
mt: !..!..!..!..!..!
sd: .!!....!!....!!.
lt: ....8.....!.....
[Samba3MeasureA 4/4]
#...1234567890123456
ac: !...!...!...!...
ch: !!8!8!8!8!!!!!!!
sd: ....8.......8...
bd: !..!!..!!..!!..!
[Samba3MeasureB 4/4]
#...1234567890123456
ac: .......8...!....
ch: .!.!..!.!..!..!.
sd: !.!.!!.!.!!.!!.!
bd: !..!!..!!..!!..!
[Samba3Break 4/4]
#...1234567890123456
ch: !!....!!..!.!...
oh: ...............!
ht: ..!.!...........
mt: ........8.......
sd: ..!.!...!..!..!.
lt: ...........8..!.
bd: !..!!..!!..!!..!
[BossaNova1MeasureA 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
rs: !.....8.....!...
bd: !.....!.!.....!.
[BossaNova1MeasureB 4/4]
#...1234567890123456
ch: !.!.!.!.!.!.!.!.
rs: ....8.....!.....
bd: !.....!.!.....!.
[BossaNova1Break 4/4]
#...1234567890123456
cy: ....8...........
ch: ..!.............
mt: ........!.!.....
rs: !...............
lt: ............8...
bd: ..!.!.........!.
[BossaNova2MeasureA 4/4]
#...1234567890123456
cy: !.!.!.!.!.!.!.!.
ch: ....8.......8...
rs: ..!..!..!..!....
bd: !.....!.!.....!.
[BossaNova2MeasureB 4/4]
#...1234567890123456
cy: !.!.!.!.!.!.!.!.
ch: ....8.......8...
rs: ..!!..!!..!!..!!
bd: !.....!.!.....!.
[BossaNova2Break 4/4]
#...1234567890123456
ac: ............8...
mt: ..!...!.........
lt: ..........!.!...
[Cha-ChaMeasureA 4/4]
#...1234567890123456
ch: ....8.......8...
ht: ..!...!.........
lt: ............!.!.
cb: !...!...!...!...
bd: !.....!.!.....!.
[Cha-ChaMeasureB 4/4]
#...1234567890123456
ch: ....8.......8...
ht: ..!!......!!....
lt: ......!!......!.
cb: !...!...!...!...
bd: !.....!.!.....!.
[Cha-ChaBreak 4/4]
#...1234567890123456
ac: ............8...
ch: ............8...
ht: ..!.....8.......
sd: ............8...
lt: ....!.!.........

