# ac: Accent
# bd: Bass drum
# sd: Snare Drum
# lt: Low tom
# mt: Medium tom
# ht: High tom
# ch: Closed hi-hat
# oh: Open hi-hat
# cy: Cymbal
# rs: Rim shot
# cp: Clap
# cb: Cowbell

# sections are pattern names, ex [pop.0], [pop.0.Break]
# number of steps = longest pattern length
# patterns are extended to correct number of steps
# example: '!.!' is extended to '!.!!.!!.' if steps = 8
# '.' - No sound on this step, '!'-sounds always play on this step
# '1'-probability of play 10%, 2-20% etc.
# accent on specific step (AC) makes louder sound 



[test1]
BD :  7.
SD : ...!
CH : !!8!8!8!8!!!!!!!


[test2]
BD : ! ..............
SD : ....8...........
CH : .!..............
OH : ........8.......
CB : .........8......
RS : ..........8.....
HT : ...........8....
LT : ............8...
MT : .............8..
CY : ..............!.


[Beatles: Sgt Peppers]
AC : .!
BD : !.......!.!.....
OH : !.
SD : ....8.......8...

[Led Zeppelin: When the Levee Breaks]
BD : ! .....8..!!....
OH : !.
SD : ....8...
CY : 2...

[James Brown: Funky President]
AC : !..!
BD : !..!...!.!!.....
SD : ....8...
CH : !.!.!.!.!...!.!.
OH : ..........8.....
