
[Pop1MeasureA 4/4]
#...1234567890123456
ac: ....!.......!...
ch: !.!.!.!.!.!.!.!.
sd: ....!.!.....8...
bd: !.......8.....!.
[Pop1MeasureB 4/4]
#...1234567890123456
ac: ....!...........
ch: !.!.!.!.!.!.!.!.
sd: ....8.....!.....
bd: !.....!.!.....!.
[Pop1Break 4/4]
#...1234567890123456
ac: ............!...
ch: !...............
sd: ..!.!.!.!.888...
lt: ..!.!.!.!.......
bd: !...............
[Pop2MeasureA 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ...!....8...!...
bd: !.....8...!..!..
[Pop2MeasureB 4/4]
#...1234567890123456
ac: .............!..
ch: !...!...!...!...
sd: ...!......8..!..
bd: !.....8.....!...
[Pop2Break 4/4]
#...1234567890123456
ac: ...!.....!......
mt: ........!!......
sd: ..!!........!!!!
bd: !...!.!...!.....
[Pop3MeasureA 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: !..!....8..!....
bd: ....!.88.!..!...
[Pop3MeasureB 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8.......8...
bd: !.88.!..!.88.!..
[Pop3Break 4/4]
#...1234567890123456
ac: ...........!....
ch: ............8...
mt: ...!............
sd: !.........!!....
lt: ................
bd: ............8...
[Pop4MeasureA 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8..!....8...
bd: !.......!.!.....
[Pop4MeasureB 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ....8..!....8...
bd: !.!.....!.!!....
[Pop4Break 4/4]
#...1234567890123456
ac: !...........!..!
ch: !...............
sd: ....!.!.!...!.!!
bd: !.........8.....
[Pop5MeasureA 4/4]
#...1234567890123456
ch: !...!...!...!...
sd: ...!!.......8...
bd: !.....8...!..!..
[Pop5MeasureB 4/4]
#...1234567890123456
ac: .............!..
ch: !...!...!...!!..
sd: ...!......!.!...
bd: !.....8......8..
[Pop5Break 4/4]
#...1234567890123456
oh: !...!...!...!...
sd: .!!!!.!!!!!.!!!!
bd: !...!...!...!...