


[Swing1MeasureA 12/8]
#...123456789012
ch: !..!..!..!..
bd: !..!..!..!..
[Swing1MeasureB 12/8]
#...123456789012
ch: !..!..!..!..
sd: ...!.....8..
bd: !..!..!..!..
[Swing1Break 12/8]
#...123456789012
ch: !..!........
sd: ......!!!!!!
bd: !..!........
[Swing2MeasureA 12/8]
#...123456789012
ch: !..!.!!..!.!
sd: ...!.....8..
bd: !..!..!..!..
[Swing2MeasureB 12/8]
#...123456789012
ch: !..!.!!..!.!
sd: ...!.....8..
bd: !..!.!!..!..
[Swing2Break 12/8]
#...123456789012
ch: ..........!.
sd: ...!...!.!!.
bd: !!!.888.!...
[Swing3MeasureA 12/8]
#...123456789012
cy: !..!..!..!.!
sd: ...!.....8..
bd: !....88.!..!
[Swing3MeasureB 12/8]
#...123456789012
cy: !..!..!..!..
sd: ...!.....8..
bd: !.!..88.!..!
[Swing3Break 12/8]
#...123456789012
oh: !..!..!..!..
mt: ....!!....!!
sd: .!!....!!...
bd: !..!..!..!..






[Shuffle1MeasureA 12/8]
#...123456789012
ch: !.!!.!!.!!.!
sd: ...!.....8..
bd: !....!!.....
[Shuffle1MeasureB 12/8]
#...123456789012
ch: !.!!.!!.!!.!
sd: ...!.....8..
bd: !....88.!...
[Shuffle1Break 12/8]
#...123456789012
ch: !...........
sd: ...!..!..!..
bd: !...!!.!!.!!
[Shuffle2MeasureA 12/8]
#...123456789012
ch: !.!!.!!.!!.!
sd: ...!.....8..
bd: !.!...!.!...
[Shuffle2MeasureB 12/8]
#...123456789012
ch: !.!!.!!.!!.!
sd: ...!.!...!..
bd: !.!...!.!...
[Shuffle2Break 12/8]
#...123456789012
ch: !..!........
sd: .!!.!!!!.!!.
bd: !..!....8..!
