; === midi options
;keyboard_keys  -- keys on computer keyboard if MIDI controller is missing
;keyboard_notes -- notes of MIDI foot controller pedal. Note velocity must be > 10

[MIDI]
keyboard_keys = 1, 2, 3, 4
keyboard_notes = 60, 62, 64, 65