[DEFAULT]
# gui buttons on top
gui :  [play] [song] [drum] [serv] [next]
prev : _prev_section
next : _next_section
play : _update_menu play
song : _update_menu song
drum : _update_menu drum
serv : _update_menu serv

#commands below are for MIDI controller
12-1 : _prev_section
13-1 : _next_section

12-6 : _update_menu play
13-6 : _update_menu song
13-7 : _update_menu drum
13-8 : _update_menu serv

