[DEFAULT]


prev : _prev_section
next : _next_section
play : _update_menu play
song : _update_menu song
drum : _update_menu drum
serv : _update_menu serv

#commands below are for MIDI controller
64-1 : _prev_section
65-1 : _next_section

64-6 :  _update_menu play
65-6 : _update_menu song
65-7 : _update_menu drum
65-8 : _update_menu serv

